<?php
/**
 * @file
 * Provides jOrgChart-library-based visualization of Book menu tree.
 */


/**
 * Implements hook_permission().
 */
function orgchart_permission() {
  return array(
    'view orgchart' => array(
      'title' => t('View org charts'),
    )
  );
}

/*function RecurseArray( $inarray ){ 
  global $base_url;
  $page = '';
  $page .= '<ul id="org" style="display:none">';
  foreach ( $inarray as $k => $v ){ 
      dsm($v);
     if ( is_array($v) && count($v) > 0 && $v == $v['below']){ 
      RecurseArray($v);
   //}elseif( $inarray['link'] && count($v['link'] > 0)){
     }else{ 
       $page .= '<ul>';
       $page .= '<li><a =href"'.$base_url.'/node/'.$v['link']['link_path'].'">'.$v['link']['link_title'].'</a></li>'; 
       $page .= '</ul>';
     }
  } 
  $page .= '</ul>';
  return $page; 
} */

function recurse_array($inarray){
  $list = '';
  foreach($inarray as $k => $v){
    dsm($v);
    $list .= '<li>'.$v['link']['link_title'].'</li>'; 
///*    if(is_array($v)){
    foreach($v['below'] as $lk => $lv){
      $list .= '<ul>'; 
      if($lv['below']){
       recurse_array($lv['below']);
      }
      else{
        $list .= '<li>'.$lv['link']['link_title'].'</li>';    
      }
      $list .= '</ul>';
    }
    //}*/
  }  
  return $list;
}

function orgchart_render() {
  global $base_url;
  $page = '';

  //drupal_add_js(drupal_get_path('module','orgchart').'/jquery.min.js');
  //drupal_add_js(drupal_get_path('module','orgchart').'/jquery-ui.min.js');
  drupal_add_js(drupal_get_path('module','orgchart').'/jquery.jOrgChart.js');
  drupal_add_js(drupal_get_path('module','orgchart').'/prettify.js');
  drupal_add_js(drupal_get_path('module','orgchart').'/orgchart.js');
  drupal_add_js(drupal_get_path('module','orgchart').'/chartdraw.js');
  drupal_add_css(drupal_get_path('module','orgchart').'/jquery.jOrgChart.css');
  drupal_add_css(drupal_get_path('module','orgchart').'/prettify.css');
  drupal_add_css(drupal_get_path('module','orgchart').'/custom.css');


  $this_nid = arg(1);

  $get_node = node_load($this_nid);

  $book_tree = menu_tree_all_data(book_menu_name($get_node->book['bid']));
  
  //dsm($book_tree);
  $page .= '<ul id="org" style="display:none">';
  foreach($book_tree as $v){
    if($v['link']){    
      $page .= '<li><a href="'.$base_url.'/'.$v['link']['link_path'].'">'.$v['link']['link_title'].'</a>';
    }
    if($v['below'] && count($v['below']) > 0){
      
      $page .= '<ul>';
      $page .= recurse_array($v['below']);
      $page .= '</ul>';
    }
  }
  $page .= '</li>';  
  $page .= '</ul>';
  $page .= '<div id="chart" class="orgChart"></div>';
  return $page;
}



